[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
crypto = "Exfqqq3q9uqYAL4z5X1G1y2hSt1A7urEQTHJnvFpzhXb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/my-deploy-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
